#ifndef PCSC2017_GROUP2_MONTECARLO_METROPOLISALGORITHM_H
#define PCSC2017_GROUP2_MONTECARLO_METROPOLISALGORITHM_H


class MonteCarlo_MetropolisAlgorithm {

};


#endif //PCSC2017_GROUP2_MONTECARLO_METROPOLISALGORITHM_H
